export type BlogCategory = 'laboral' | 'arriendo' | 'familia' | 'penal';
export type BlogTopic = 'divorcio' | 'pension' | 'finiquito' | 'despido' | 'arriendo' | 'penal' | 'familia';

export interface ArticleConversionConfig {
  category: BlogCategory;
  topic: BlogTopic;
  searchCategory: string;
  inArticleMessage: string;
  inArticleButton: string;
  preConclusionDescription: string;
  preConclusionLink: string;
  preConclusionButton?: string;
}

export const blogConversionConfig: Record<string, ArticleConversionConfig> = {
  'divorcio-unilateral-chile-2026': {
    category: 'familia',
    topic: 'divorcio',
    searchCategory: 'Derecho de Familia',
    inArticleMessage: '¿Quieres iniciar un divorcio unilateral? Un abogado de familia puede ayudarte a reunir las pruebas y tramitar el proceso.',
    inArticleButton: 'Ver abogados de familia',
    preConclusionDescription: 'Si cumples los requisitos para divorciarte pero no sabes cómo iniciar la demanda, puedes comparar abogados especializados en divorcio unilateral y agendar una consulta online.',
    preConclusionLink: '/abogado-divorcio-unilateral',
  },
  'divorcio-de-mutuo-acuerdo-chile-2026': {
    category: 'familia',
    topic: 'divorcio',
    searchCategory: 'Derecho de Familia',
    inArticleMessage: '¿Quieres divorciarte de mutuo acuerdo? Un abogado de familia puede redactar el acuerdo completo y tramitar el proceso ante el tribunal.',
    inArticleButton: 'Ver abogados de familia',
    preConclusionDescription: 'Si ambos están de acuerdo en divorciarse, un abogado especializado puede preparar el acuerdo sobre hijos y bienes y acelerar el trámite.',
    preConclusionLink: '/abogado-divorcio-unilateral',
  },
  'compensacion-economica-divorcio-chile-2026': {
    category: 'familia',
    topic: 'divorcio',
    searchCategory: 'Derecho de Familia',
    inArticleMessage: '¿Crees que tienes derecho a compensación económica? Un abogado de familia puede evaluar tu caso y estimar el monto que podrías reclamar.',
    inArticleButton: 'Ver abogados de familia',
    preConclusionDescription: 'La compensación económica depende de pruebas concretas. Compara abogados especializados en divorcio y patrimonio familiar antes de iniciar la demanda.',
    preConclusionLink: '/abogado-divorcio-unilateral',
  },
  'mediacion-familiar-chile-2026': {
    category: 'familia',
    topic: 'familia',
    searchCategory: 'Derecho de Familia',
    inArticleMessage: '¿Tienes una audiencia de mediación familiar próxima? Un abogado puede prepararte y representarte para proteger tus derechos.',
    inArticleButton: 'Ver abogados de familia',
    preConclusionDescription: 'La mediación familiar es obligatoria en muchos conflictos. Un abogado especializado puede orientarte antes, durante y después del proceso.',
    preConclusionLink: '/search?specialty=Derecho%20de%20Familia',
  },
  'regimen-de-visitas-chile-2026': {
    category: 'familia',
    topic: 'familia',
    searchCategory: 'Derecho de Familia',
    inArticleMessage: '¿Necesitas modificar o establecer un régimen de visitas? Un abogado de familia puede ayudarte a presentar la solicitud correctamente.',
    inArticleButton: 'Ver abogados de familia',
    preConclusionDescription: 'El régimen de visitas protege el vínculo con tus hijos. Compara abogados de familia y agenda una consulta para evaluar tu situación.',
    preConclusionLink: '/search?specialty=Derecho%20de%20Familia',
  },
  'cuidado-personal-hijos-chile-2026': {
    category: 'familia',
    topic: 'familia',
    searchCategory: 'Derecho de Familia',
    inArticleMessage: '¿Disputas sobre el cuidado personal de tus hijos? Un abogado de familia puede representarte y defender el interés superior del niño.',
    inArticleButton: 'Ver abogados de familia',
    preConclusionDescription: 'El cuidado personal define con quién viven los hijos. Compara abogados especializados y recibe orientación antes de presentar tu demanda.',
    preConclusionLink: '/search?specialty=Derecho%20de%20Familia',
  },
  'derecho-de-familia-chile-2026': {
    category: 'familia',
    topic: 'familia',
    searchCategory: 'Derecho de Familia',
    inArticleMessage: '¿Necesitas ayuda con un problema familiar? Compara abogados especializados en divorcio, alimentos y cuidado personal.',
    inArticleButton: 'Ver abogados de familia',
    preConclusionDescription: 'Los conflictos familiares requieren estrategia y plazos estrictos. Encuentra abogados verificados y agenda tu consulta online.',
    preConclusionLink: '/search?specialty=Derecho%20de%20Familia',
  },
  'deuda-pension-alimentos-chile-2026': {
    category: 'familia',
    topic: 'pension',
    searchCategory: 'Derecho de Familia',
    inArticleMessage: '¿Tienes deuda de pensión de alimentos o quieres cobrarla? Un abogado de familia puede orientarte sobre embargos, DICOM y demandas.',
    inArticleButton: 'Ver abogados de pensión de alimentos',
    preConclusionDescription: 'La deuda de alimentos puede generar consecuencias graves. Compara abogados especializados en pensiones alimenticias y actúa a tiempo.',
    preConclusionLink: '/search?specialty=Derecho%20de%20Familia',
    preConclusionButton: 'Ver abogados de pensión de alimentos',
  },
  'aumento-pension-alimentos-chile-2026': {
    category: 'familia',
    topic: 'pension',
    searchCategory: 'Derecho de Familia',
    inArticleMessage: '¿Necesitas aumentar la pensión de alimentos? Un abogado puede evaluar si cumples los requisitos y presentar la demanda.',
    inArticleButton: 'Ver abogados de pensión de alimentos',
    preConclusionDescription: 'El aumento de alimentos requiere acreditar un cambio sustancial en las necesidades o ingresos. Compara abogados y revisa tu caso antes de demandar.',
    preConclusionLink: '/search?specialty=Derecho%20de%20Familia',
    preConclusionButton: 'Ver abogados de pensión de alimentos',
  },
  'rebaja-pension-alimentos-chile-2026': {
    category: 'familia',
    topic: 'pension',
    searchCategory: 'Derecho de Familia',
    inArticleMessage: '¿Quieres solicitar una rebaja de pensión de alimentos? Un abogado puede analizar si tienes fundamentos legales para pedirla.',
    inArticleButton: 'Ver abogados de pensión de alimentos',
    preConclusionDescription: 'La rebaja de alimentos no es automática: debes acreditar un cambio en tu capacidad económica. Compara abogados especializados y evalúa tu caso.',
    preConclusionLink: '/search?specialty=Derecho%20de%20Familia',
    preConclusionButton: 'Ver abogados de pensión de alimentos',
  },
  'como-calcular-tu-finiquito-chile-2026': {
    category: 'laboral',
    topic: 'finiquito',
    searchCategory: 'Derecho Laboral',
    inArticleMessage: '¿No estás seguro si el monto que te ofrecen es correcto? Un abogado laboral puede revisar tu finiquito antes de que lo firmes.',
    inArticleButton: 'Ver abogados laborales',
    preConclusionDescription: 'Antes de firmar, verifica que tu finiquito incluya todas las indemnizaciones y vacaciones que te corresponden. Compara abogados laborales y revisa tu caso.',
    preConclusionLink: '/search?specialty=Derecho%20Laboral',
    preConclusionButton: 'Revisar mi finiquito con un abogado',
  },
  'reserva-de-derechos-finiquito-chile-2026': {
    category: 'laboral',
    topic: 'finiquito',
    searchCategory: 'Derecho Laboral',
    inArticleMessage: '¿Vas a firmar tu finiquito con reserva de derechos? Un abogado laboral puede orientarte sobre cómo hacerlo correctamente.',
    inArticleButton: 'Ver abogados laborales',
    preConclusionDescription: 'Firmar con reserva de derechos te permite cobrar y aún reclamar diferencias. Compara abogados laborales antes de tomar una decisión.',
    preConclusionLink: '/search?specialty=Derecho%20Laboral',
  },
  'cuanto-me-corresponde-anos-de-servicio-chile-2026': {
    category: 'laboral',
    topic: 'finiquito',
    searchCategory: 'Derecho Laboral',
    inArticleMessage: '¿Quieres calcular cuánto te corresponde por años de servicio? Un abogado laboral puede verificar el monto según tu sueldo y antigüedad.',
    inArticleButton: 'Ver abogados laborales',
    preConclusionDescription: 'La indemnización por años de servicio depende de tu sueldo y tiempo trabajado. Compara abogados laborales y confirma que el cálculo sea correcto.',
    preConclusionLink: '/search?specialty=Derecho%20Laboral',
  },
  'que-pasa-si-no-firmo-el-finiquito-chile-2026': {
    category: 'laboral',
    topic: 'finiquito',
    searchCategory: 'Derecho Laboral',
    inArticleMessage: '¿Te presionan para firmar un finiquito que no te convence? Un abogado laboral puede explicarte tus opciones legales.',
    inArticleButton: 'Ver abogados laborales',
    preConclusionDescription: 'No firmar el finiquito no significa perder tus derechos. Compara abogados laborales y define la mejor estrategia para tu caso.',
    preConclusionLink: '/search?specialty=Derecho%20Laboral',
  },
  'como-demandar-por-despido-injustificado-chile-2026': {
    category: 'laboral',
    topic: 'despido',
    searchCategory: 'Derecho Laboral',
    inArticleMessage: '¿Fuiste despedido y crees que fue injustificado? Un abogado laboral puede evaluar si tienes derecho a demandar y calcular indemnizaciones.',
    inArticleButton: 'Ver abogados laborales',
    preConclusionDescription: 'El plazo para demandar por despido injustificado es corto. Compara abogados laborales verificados y actúa antes de que venza tu derecho.',
    preConclusionLink: '/search?specialty=Derecho%20Laboral',
    preConclusionButton: 'Ver abogados laborales disponibles',
  },
  'cuanto-dura-juicio-laboral-despido-injustificado-chile-2026': {
    category: 'laboral',
    topic: 'despido',
    searchCategory: 'Derecho Laboral',
    inArticleMessage: '¿Estás evaluando demandar por despido injustificado? Un abogado laboral puede estimar plazos y preparar tu estrategia.',
    inArticleButton: 'Ver abogados laborales',
    preConclusionDescription: 'Conocer la duración del juicio te ayuda a planificar. Compara abogados laborales especializados en despidos y agenda una consulta.',
    preConclusionLink: '/search?specialty=Derecho%20Laboral',
  },
  'despido-injustificado-chile-2026': {
    category: 'laboral',
    topic: 'despido',
    searchCategory: 'Derecho Laboral',
    inArticleMessage: '¿Crees que tu despido fue injustificado? Un abogado laboral puede revisar la causal invocada y tus indemnizaciones.',
    inArticleButton: 'Ver abogados laborales',
    preConclusionDescription: 'Muchos despidos no cumplen los requisitos legales. Compara abogados laborales y evalúa si conviene demandar o negociar.',
    preConclusionLink: '/search?specialty=Derecho%20Laboral',
  },
  'me-pueden-despedir-sin-motivo-chile-2026': {
    category: 'laboral',
    topic: 'despido',
    searchCategory: 'Derecho Laboral',
    inArticleMessage: '¿Te despidieron invocando necesidades de la empresa? Un abogado laboral puede verificar si el despido cumple la ley y qué te corresponde cobrar.',
    inArticleButton: 'Ver abogados laborales',
    preConclusionDescription: 'Aunque pueden despedirte sin acreditar una falta, deben pagarte indemnización. Compara abogados laborales y revisa si el monto es correcto.',
    preConclusionLink: '/search?specialty=Derecho%20Laboral',
  },
  'me-pueden-despedir-con-licencia-medica-chile-2026': {
    category: 'laboral',
    topic: 'despido',
    searchCategory: 'Derecho Laboral',
    inArticleMessage: '¿Te despidieron estando con licencia médica? Un abogado laboral puede evaluar si el despido es nulo o injustificado.',
    inArticleButton: 'Ver abogados laborales',
    preConclusionDescription: 'Despedir durante licencia médica puede ser ilegal. Compara abogados laborales y actúa rápido para proteger tus derechos.',
    preConclusionLink: '/search?specialty=Derecho%20Laboral',
  },
  'autodespido-chile-2026': {
    category: 'laboral',
    topic: 'despido',
    searchCategory: 'Derecho Laboral',
    inArticleMessage: '¿Estás evaluando un autodespido por incumplimientos graves del empleador? Un abogado laboral puede confirmar si cumples los requisitos.',
    inArticleButton: 'Ver abogados laborales',
    preConclusionDescription: 'El autodespido exige pruebas sólidas de incumplimiento. Compara abogados laborales antes de renunciar con derecho a indemnización.',
    preConclusionLink: '/search?specialty=Derecho%20Laboral',
  },
  'orden-desalojo-chile-2026': {
    category: 'arriendo',
    topic: 'arriendo',
    searchCategory: 'Derecho Civil',
    inArticleMessage: '¿Recibiste una orden de desalojo o estás por obtenerla? Un abogado especializado puede evaluar tus opciones legales.',
    inArticleButton: 'Ver abogados de arriendo',
    preConclusionDescription: 'Una orden de desalojo puede llevar al lanzamiento forzado. Compara abogados especializados en arriendos y desalojos y actúa a tiempo.',
    preConclusionLink: '/search?specialty=Derecho%20Civil',
  },
  'cuanto-demora-juicio-desalojo-chile-2026': {
    category: 'arriendo',
    topic: 'arriendo',
    searchCategory: 'Derecho Civil',
    inArticleMessage: '¿Estás en un juicio de desalojo o piensas iniciarlo? Un abogado puede orientarte sobre plazos y estrategia.',
    inArticleButton: 'Ver abogados de arriendo',
    preConclusionDescription: 'Conocer los plazos del desalojo te permite actuar con anticipación. Compara abogados especializados en arriendos y protege tu propiedad o tus derechos.',
    preConclusionLink: '/search?specialty=Derecho%20Civil',
  },
  'cuantos-meses-debo-arriendo-para-que-me-desalojen-chile-2026': {
    category: 'arriendo',
    topic: 'arriendo',
    searchCategory: 'Derecho Civil',
    inArticleMessage: '¿Llevas meses sin pagar el arriendo y temes un desalojo? Un abogado puede explicarte en qué etapa está tu riesgo y qué opciones tienes.',
    inArticleButton: 'Ver abogados de arriendo',
    preConclusionDescription: 'La deuda acumulada puede derivar en demanda y desalojo. Compara abogados de arriendo y evalúa si conviene negociar o defender tu caso.',
    preConclusionLink: '/search?specialty=Derecho%20Civil',
  },
  'tacita-reconduccion-chile-2026': {
    category: 'arriendo',
    topic: 'arriendo',
    searchCategory: 'Derecho Civil',
    inArticleMessage: '¿Tu arrendatario sigue en la propiedad después del plazo? Un abogado puede orientarte sobre tacita reconducción y desalojo.',
    inArticleButton: 'Ver abogados de arriendo',
    preConclusionDescription: 'La tacita reconducción cambia tus derechos como arrendador. Compara abogados especializados antes de actuar por tu cuenta.',
    preConclusionLink: '/search?specialty=Derecho%20Civil',
  },
  'dicom-deuda-arriendo-chile-2026': {
    category: 'arriendo',
    topic: 'arriendo',
    searchCategory: 'Derecho Civil',
    inArticleMessage: '¿Te reportaron en DICOM por deuda de arriendo? Un abogado puede orientarte sobre cobro, negociación y defensa.',
    inArticleButton: 'Ver abogados de arriendo',
    preConclusionDescription: 'Un reporte en DICOM por arriendo impago puede afectar tu historial crediticio. Compara abogados y define la mejor estrategia.',
    preConclusionLink: '/search?specialty=Derecho%20Civil',
  },
  'me-pueden-demandar-por-no-pagar-el-arriendo-chile-2026': {
    category: 'arriendo',
    topic: 'arriendo',
    searchCategory: 'Derecho Civil',
    inArticleMessage: '¿Te demandaron por no pagar el arriendo? Un abogado especializado puede defender tu caso o negociar un acuerdo.',
    inArticleButton: 'Ver abogados de arriendo',
    preConclusionDescription: 'Ignorar una demanda por arriendo impago aumenta el riesgo de desalojo. Compara abogados de arriendo y responde a tiempo.',
    preConclusionLink: '/search?specialty=Derecho%20Civil',
  },
  'reajuste-arriendo-ipc-chile-2026': {
    category: 'arriendo',
    topic: 'arriendo',
    searchCategory: 'Derecho Civil',
    inArticleMessage: '¿Te subieron el arriendo por IPC y no estás seguro si es legal? Un abogado puede revisar el reajuste y tus derechos.',
    inArticleButton: 'Ver abogados de arriendo',
    preConclusionDescription: 'No todo reajuste de arriendo es válido. Compara abogados especializados y verifica si el aumento cumple la ley.',
    preConclusionLink: '/search?specialty=Derecho%20Civil',
  },
  'que-pasa-si-no-tengo-contrato-de-arriendo-chile-2026': {
    category: 'arriendo',
    topic: 'arriendo',
    searchCategory: 'Derecho Civil',
    inArticleMessage: '¿Arriendas o arriendas sin contrato escrito? Un abogado puede explicarte qué derechos tienes igualmente.',
    inArticleButton: 'Ver abogados de arriendo',
    preConclusionDescription: 'Aun sin contrato escrito existen derechos y obligaciones. Compara abogados de arriendo y regulariza tu situación.',
    preConclusionLink: '/search?specialty=Derecho%20Civil',
  },
  'no-devuelven-garantia-arriendo-chile-2026': {
    category: 'arriendo',
    topic: 'arriendo',
    searchCategory: 'Derecho Civil',
    inArticleMessage: '¿No te devuelven la garantía del arriendo? Un abogado puede ayudarte a exigir la restitución y calcular intereses.',
    inArticleButton: 'Ver abogados de arriendo',
    preConclusionDescription: 'Retener la garantía sin fundamento puede ser ilegal. Compara abogados especializados y recupera lo que te corresponde.',
    preConclusionLink: '/search?specialty=Derecho%20Civil',
  },
  'me-subieron-el-arriendo-que-hago-2026': {
    category: 'arriendo',
    topic: 'arriendo',
    searchCategory: 'Derecho Civil',
    inArticleMessage: '¿Te subieron el arriendo y no sabes si puedes rechazarlo? Un abogado puede revisar si el aumento es legal.',
    inArticleButton: 'Ver abogados de arriendo',
    preConclusionDescription: 'Aceptar un aumento ilegal puede perjudicarte a largo plazo. Compara abogados de arriendo y evalúa tus opciones.',
    preConclusionLink: '/search?specialty=Derecho%20Civil',
  },
  'me-quieren-desalojar-que-hago-chile-2026': {
    category: 'arriendo',
    topic: 'arriendo',
    searchCategory: 'Derecho Civil',
    inArticleMessage: '¿Te quieren desalojar y no sabes qué hacer? Un abogado especializado puede evaluar si el procedimiento es legal.',
    inArticleButton: 'Ver abogados de arriendo',
    preConclusionDescription: 'Actuar temprano en un desalojo puede marcar la diferencia. Compara abogados de arriendo y protege tus derechos.',
    preConclusionLink: '/search?specialty=Derecho%20Civil',
  },
  'ley-devuelveme-mi-casa-chile-2026': {
    category: 'arriendo',
    topic: 'arriendo',
    searchCategory: 'Derecho Civil',
    inArticleMessage: '¿Quieres recuperar tu propiedad bajo la ley Devuélveme mi Casa? Un abogado puede evaluar si tu caso califica.',
    inArticleButton: 'Ver abogados de arriendo',
    preConclusionDescription: 'La ley Devuélveme mi Casa tiene requisitos específicos. Compara abogados especializados y verifica si puedes usar este procedimiento.',
    preConclusionLink: '/search?specialty=Derecho%20Civil',
  },
  'contrato-de-arriendo-chile-2026': {
    category: 'arriendo',
    topic: 'arriendo',
    searchCategory: 'Derecho Civil',
    inArticleMessage: '¿Vas a firmar o redactar un contrato de arriendo? Un abogado puede revisar las cláusulas y proteger tus intereses.',
    inArticleButton: 'Ver abogados de arriendo',
    preConclusionDescription: 'Un contrato mal redactado puede generar conflictos costosos. Compara abogados de arriendo antes de firmar.',
    preConclusionLink: '/search?specialty=Derecho%20Civil',
  },
  'como-desalojar-a-una-persona-de-mi-propiedad-chile-2026': {
    category: 'arriendo',
    topic: 'arriendo',
    searchCategory: 'Derecho Civil',
    inArticleMessage: '¿Necesitas desalojar a alguien de tu propiedad? Un abogado puede iniciar el juicio correcto según tu situación.',
    inArticleButton: 'Ver abogados de arriendo',
    preConclusionDescription: 'Desalojar por tu cuenta puede ser ilegal. Compara abogados especializados y recupera tu propiedad por la vía judicial.',
    preConclusionLink: '/search?specialty=Derecho%20Civil',
  },
  'como-desalojar-a-un-familiar-de-mi-casa-chile-2026': {
    category: 'arriendo',
    topic: 'arriendo',
    searchCategory: 'Derecho Civil',
    inArticleMessage: '¿Un familiar ocupa tu propiedad y no se va? Un abogado puede orientarte sobre comodato, precario o desalojo.',
    inArticleButton: 'Ver abogados de arriendo',
    preConclusionDescription: 'Desalojar a un familiar requiere el procedimiento correcto. Compara abogados y evita errores que retrasen el proceso.',
    preConclusionLink: '/search?specialty=Derecho%20Civil',
  },
  'arrendador-puede-cambiar-cerradura-chile-2026': {
    category: 'arriendo',
    topic: 'arriendo',
    searchCategory: 'Derecho Civil',
    inArticleMessage: '¿Tu arrendador cambió la cerradura o estás considerando hacerlo? Un abogado puede explicarte qué es legal y qué no.',
    inArticleButton: 'Ver abogados de arriendo',
    preConclusionDescription: 'Cambiar cerraduras sin autorización judicial puede ser delito. Compara abogados de arriendo y resuelve el conflicto legalmente.',
    preConclusionLink: '/search?specialty=Derecho%20Civil',
  },
  'derecho-arrendamiento-chile-guia-completa-2026': {
    category: 'arriendo',
    topic: 'arriendo',
    searchCategory: 'Derecho Civil',
    inArticleMessage: '¿Tienes un conflicto de arrendamiento? Compara abogados especializados en contratos, desalojos y cobro de rentas.',
    inArticleButton: 'Ver abogados de arriendo',
    preConclusionDescription: 'El arrendamiento tiene reglas específicas en Chile. Encuentra abogados verificados y resuelve tu conflicto con asesoría profesional.',
    preConclusionLink: '/search?specialty=Derecho%20Civil',
  },
  'derecho-penal-chile-2026': {
    category: 'penal',
    topic: 'penal',
    searchCategory: 'Derecho Penal',
    inArticleMessage: '¿Necesitas defensa penal o quieres interponer una querella? Compara abogados penalistas disponibles para ayudarte.',
    inArticleButton: 'Ver abogados penales',
    preConclusionDescription: 'En materia penal cada plazo cuenta. Encuentra abogados penalistas verificados y agenda una consulta urgente.',
    preConclusionLink: '/search?specialty=Derecho%20Penal',
    preConclusionButton: 'Ver abogados penales disponibles',
  },
};
