import type { DocumentField } from '../../types'

const schema: DocumentField[] = [
  {
    id: 'creditor_name',
    label: 'Nombre completo',
    placeholder: 'Juan Pérez González',
    helpText: 'Nombre del acreedor (quien presta el dinero)',
    validation: 'text',
    group: 'Datos del acreedor',
    required: true,
    pdfField: 'creditorName',
    formatter: 'uppercase',
  },
  {
    id: 'creditor_rut',
    label: 'RUT',
    placeholder: '12.345.678-9',
    helpText: 'Sin puntos, con guión',
    // example: '12345678-9',
    validation: 'rut',
    group: 'Datos del acreedor',
    required: true,
    pdfField: 'creditorRut',
    mask: 'rut',
  },
  {
    id: 'creditor_address',
    label: 'Domicilio',
    placeholder: 'Av. Siempre Viva 123, Santiago',
    group: 'Datos del acreedor',
    required: true,
    pdfField: 'creditorAddress',
    formatter: 'uppercase',
  },
  {
    id: 'creditor_city',
    label: 'Ciudad',
    placeholder: 'Santiago',
    group: 'Datos del acreedor',
    required: true,
    pdfField: 'creditorCity',
    formatter: 'uppercase',
  },
  {
    id: 'debtor_name',
    label: 'Nombre completo',
    placeholder: 'María Soto Martínez',
    helpText: 'Nombre del deudor (quien recibe el dinero y se obliga a pagar)',
    validation: 'text',
    group: 'Datos del deudor',
    required: true,
    pdfField: 'debtorName',
    formatter: 'uppercase',
  },
  {
    id: 'debtor_rut',
    label: 'RUT',
    placeholder: '12.345.678-9',
    helpText: 'Sin puntos, con guión',
    //example: '12345678-9',
    validation: 'rut',
    group: 'Datos del deudor',
    required: true,
    pdfField: 'debtorRut',
    mask: 'rut',
  },
  {
    id: 'debtor_address',
    label: 'Domicilio',
    placeholder: 'Calle Los Olivos 456, Ñuñoa',
    group: 'Datos del deudor',
    required: true,
    pdfField: 'debtorAddress',
    formatter: 'uppercase',
  },
  {
    id: 'debtor_city',
    label: 'Ciudad',
    placeholder: 'Santiago',
    group: 'Datos del deudor',
    required: true,
    pdfField: 'debtorCity',
    formatter: 'uppercase',
  },
  {
    id: 'has_interest',
    label: '¿Incluye intereses?',
    group: 'Monto y condiciones',
    required: true,
    pdfField: 'hasInterest',
    type: 'select',
    options: [
      { value: 'no', label: 'No, sin intereses' },
      { value: 'yes', label: 'Sí, con intereses' },
    ],
    defaultValue: 'no',
  },
  {
    id: 'amount',
    label: 'Monto del préstamo ($)',
    placeholder: '2.500.000',
    helpText: 'Monto en pesos chilenos que se presta',
    validation: 'number',
    group: 'Monto y condiciones',
    required: true,
    pdfField: 'amount',
    type: 'number',
    formatter: 'clp',
  },
  {
    id: 'amount_words',
    label: 'Monto en palabras',
    placeholder: 'Dos millones quinientos mil pesos',
    helpText: 'Se completa automáticamente según el monto indicado',
    validation: 'text',
    group: 'Monto y condiciones',
    required: true,
    pdfField: 'amountWords',
    formatter: 'uppercase',
  },
  {
    id: 'interest_rate',
    label: 'Tasa de interés mensual (%)',
    placeholder: '1.5',
    helpText: 'Porcentaje de interés mensual. Ej: 1.5 = 1,5% mensual',
    example: '1.5',
    validation: 'number',
    group: 'Monto y condiciones',
    required: false,
    pdfField: 'interestRate',
    type: 'number',
    conditional: {
      field: 'has_interest',
      value: 'yes',
    },
  },
  {
    id: 'total_with_interest',
    label: 'Monto total con intereses ($)',
    placeholder: '2.875.000',
    helpText: 'Monto final a pagar incluyendo intereses',
    validation: 'number',
    group: 'Monto y condiciones',
    required: false,
    pdfField: 'totalWithInterest',
    type: 'number',
    formatter: 'clp',
    conditional: {
      field: 'has_interest',
      value: 'yes',
    },
  },
  {
    id: 'issue_date',
    label: 'Fecha de emisión',
    placeholder: '2025-01-15',
    validation: 'date',
    group: 'Fechas',
    required: true,
    pdfField: 'issueDate',
    type: 'date',
  },
  {
    id: 'maturity_date',
    label: 'Fecha de vencimiento',
    placeholder: '2025-07-15',
    helpText: 'Fecha en que el deudor debe pagar',
    validation: 'date',
    group: 'Fechas',
    required: true,
    pdfField: 'maturityDate',
    type: 'date',
  },
  {
    id: 'payment_place',
    label: 'Lugar de pago',
    placeholder: 'Domicilio del acreedor',
    helpText: 'Dirección o lugar donde se debe realizar el pago',
    group: 'Pago',
    required: true,
    pdfField: 'paymentPlace',
    formatter: 'uppercase',
  },
]

export default schema